//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assortiment
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTCHETI
    {
        public int Id_otchet { get; set; }
        public Nullable<System.DateTime> data_otchet { get; set; }
        public Nullable<int> ostatok_na_saite { get; set; }
        public Nullable<int> obyazatelno_na_sclade { get; set; }
        public Nullable<int> zakupit { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Id_assorti { get; set; }
    
        public virtual ASSORTIMENT ASSORTIMENT { get; set; }
        public virtual USER USER { get; set; }
    }
}
